insert into Course (courseID, courseAcronym, courseName, credits, studentCap, courseDescription, section) values (1, 'ADA102', 'PB', 4, 351, '(｡◕ ∀ ◕｡)', 'B');
insert into Course (courseID, courseAcronym, courseName, credits, studentCap, courseDescription, section) values (2, 'BIO505', 'PB', 4, 101, '🐵 🙈 🙉 🙊', 'A');
insert into Course (courseID, courseAcronym, courseName, credits, studentCap, courseDescription, section) values (3, 'ADA102', 'IQB', 3, 68, 'NULL', 'A');
insert into Course (courseID, courseAcronym, courseName, credits, studentCap, courseDescription, section) values (4, 'CSE202', 'PB', 4, 375, '田中さんにあげて下さい', 'C');
insert into Course (courseID, courseAcronym, courseName, credits, studentCap, courseDescription, section) values (5, 'MTH101', 'PB', 3, 395, '1E2', 'A');
insert into Course (courseID, courseAcronym, courseName, credits, studentCap, courseDescription, section) values (6, 'BIO505', 'PB', 3, 279, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 'C');
insert into Course (courseID, courseAcronym, courseName, credits, studentCap, courseDescription, section) values (7, 'BIO505', 'IQB', 2, 267, '​', 'C');
insert into Course (courseID, courseAcronym, courseName, credits, studentCap, courseDescription, section) values (8, 'BIO505', 'ADA', 4, 248, '-1E2', 'A');
insert into Course (courseID, courseAcronym, courseName, credits, studentCap, courseDescription, section) values (9, 'ADA102', 'PB', 3, 440, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 'B');
insert into Course (courseID, courseAcronym, courseName, credits, studentCap, courseDescription, section) values (10, 'BIO505', 'ADA', 4, 242, '᠎', 'C');
