# Generated by Django 3.1.7 on 2021-04-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20210407_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'UserRole', 'verbose_name_plural': 'UserRoles'},
        ),
    ]
