# Generated by Django 3.1.7 on 2021-04-07 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0003_auto_20210407_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.CharField(default='Hello World', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PreReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preReqs', to='Core.course')),
                ('preReqCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preReqOf', to='Core.course')),
            ],
            options={
                'verbose_name': 'PreReq',
                'verbose_name_plural': 'PreReqs',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=500)),
                ('parentComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentOf', to='Core.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AntiReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiReqCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antiReqOf', to='Core.course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antiReqs', to='Core.course')),
            ],
            options={
                'verbose_name': 'AntiReq',
                'verbose_name_plural': 'AntiReqs',
            },
        ),
    ]
